name: Trivy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Docker
    types: completed

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - alpine
          - debian
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Run Trivy vulnerability scanner
        if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
        uses: aquasecurity/trivy-action@0.34.1
        with:
          scan-ref: ${{ github.repository_owner }}/relate:python${{ matrix.python-version }}-${{ matrix.os }}
          scanners: vuln
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        if: hashFiles('trivy.txt')
        run: |
          {
            echo '### Security Output'
            echo '<details><summary>Click to expand</summary>'
            echo ''
            echo '```terraform'
            cat trivy.txt
            echo '```'
            echo '</details>'
          } >> ${GITHUB_STEP_SUMMARY}
